--- 
framework: 
  AdminMode: 0
  DevelMode: 0
  ApplicationClass: Ascension
  ApplicationName: Ascension
  ApplicationUUID: E148B5CA-1A17-11DC-97F0-A2ADEC34D909
  ConfigFileVersion: 2
  Database: 
    CheckSchema: 1
    Database: ascension
    Driver: SQLite
    Host: localhost
    Password: ''
    RecordBaseClass: Jifty::DBI::Record::Cachable
    User: ''
    Version: 0.0.5
  L10N: 
    PoDir: share/po
  LogLevel: INFO
  Mailer: Sendmail
  MailerArgs: []

  Plugins: 
    - LetMe: {}
    - SkeletonApp: {}
    - REST: {}
    - Halo: {}
    - ErrorTemplates: {}
    - OnlineDocs: {}
    - CompressedCSSandJS: {}
    - AdminUI: {}
    - User: {}

  PubSub: 
    Backend: Memcached
    Enable: ~
  SkipAccessControl: 0
  TemplateClass: Ascension::View
  Web: 
    BaseURL: http://localhost
    DataDir: var/mason
    Globals: []

    MasonConfig: 
      autoflush: 0
      default_escape_flags: h
      error_format: text
      error_mode: fatal
    Port: 8888
    ServeStaticFiles: 1
    StaticRoot: share/web/static
    TemplateRoot: share/web/templates
